dist: trusty
sudo: false

language:
  - cpp

install:
  - mkdir ~/googletest
  - cd ~/googletest
  - wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest googletest-release-1.8.0
  - make install

script:
  - mkdir build
  - cd build
  - cmake -D GTEST_ROOT:PATH=$HOME/googletest ..
  - make
  - make test

notifications:
  email: false
