jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/circleci-googletest
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
        - run:
            name: Install CMake
            command: |
              apt-get -y -q update
              apt-get -y -q install cmake
        - run:
            name: Install Google Test
            # This option doesn't seem to work.
            #working_directory: ~/googletest
            command: |
              mkdir ~/googletest
              cd ~/googletest
              wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
              cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.0
              make install
        - checkout
        - run:
            name: CMake build files
            command: |
              mkdir build
              cd build
              cmake -D GTEST_ROOT:PATH=$HOME/googletest ..
        - run: |
            cd build
            make
        - run: mkdir -p $TEST_RESULTS
        - run:
            name: Run unit tests
            environment:
              GTEST_OUTPUT: "xml:$TEST_RESULTS"
            command: |
              cd build
              make test
        - store_test_results:
            path: $TEST_RESULTS
